import { describe, expect, it } from 'bun:test';
import { youtube_v3 } from 'googleapis';
import { mapCaptionItem } from '../lib/youtube';

function makeCaption(
  trackKind: string | undefined = 'standard',
  audioTrackType: string | undefined = 'unknown',
  snippet: youtube_v3.Schema$CaptionSnippet = {},
): youtube_v3.Schema$Caption {
  return {
    id: 'caption-id',
    snippet: {
      videoId: 'video-id',
      language: 'en',
      trackKind,
      audioTrackType,
      ...snippet,
    },
  };
}

describe('mapCaptionItem', () => {
  it('classifies a standard caption as manual even when audioTrackType is unknown', () => {
    const caption = mapCaptionItem(makeCaption('standard', 'unknown'));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });

  it('classifies ASR captions as automatic', () => {
    const caption = mapCaptionItem(makeCaption('ASR', 'unknown'));

    expect(caption.trackKind).toBe('automatic');
    expect(caption.isAutoGenerated).toBe(true);
  });

  it('normalizes lowercase ASR values returned by the API', () => {
    const caption = mapCaptionItem(makeCaption('asr', 'unknown'));

    expect(caption.trackKind).toBe('automatic');
    expect(caption.isAutoGenerated).toBe(true);
  });

  it('classifies forced captions as automatic', () => {
    const caption = mapCaptionItem(makeCaption('forced', 'unknown'));

    expect(caption.trackKind).toBe('automatic');
    expect(caption.isAutoGenerated).toBe(true);
  });

  it('ignores audioTrackType when identifying automatic captions', () => {
    const caption = mapCaptionItem(makeCaption('standard', 'commentary'));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });

  it('falls back to manual for an unknown track kind', () => {
    const caption = mapCaptionItem(makeCaption('unexpected'));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });

  it('falls back to manual when track kind is absent', () => {
    const caption = mapCaptionItem(makeCaption(undefined));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });
});

// Issue #147: these five flags were hardcoded to `false` while the API already
// returned real values in the `snippet` part, so a draft or failed track was
// reported as an ordinary live one.
describe('mapCaptionItem track state', () => {
  it('reads the accessibility and draft flags from the snippet', () => {
    const caption = mapCaptionItem(makeCaption('standard', 'unknown', {
      isCC: true,
      isLarge: true,
      isEasyReader: true,
      isDraft: true,
      isAutoSynced: true,
    }));

    expect(caption.isClosedCaptions).toBe(true);
    expect(caption.isLarge).toBe(true);
    expect(caption.isEasyReader).toBe(true);
    expect(caption.isDraft).toBe(true);
    expect(caption.isAutoSynced).toBe(true);
  });

  it('defaults the flags to false when the API omits them', () => {
    const caption = mapCaptionItem(makeCaption('standard'));

    expect(caption.isClosedCaptions).toBe(false);
    expect(caption.isLarge).toBe(false);
    expect(caption.isEasyReader).toBe(false);
    expect(caption.isDraft).toBe(false);
    expect(caption.isAutoSynced).toBe(false);
  });

  // Live-verified by uploading a track with --draft: YouTube reports it as
  // `status: serving` alongside `isDraft: true`. The two fields are
  // independent, so a visibility check keyed off status alone is wrong.
  it('keeps status and isDraft independent, as the API reports them', () => {
    const caption = mapCaptionItem(makeCaption('standard', 'unknown', {
      status: 'serving',
      isDraft: true,
    }));

    expect(caption.status).toBe('serving');
    expect(caption.isDraft).toBe(true);
  });

  it('narrows the documented statuses', () => {
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { status: 'serving' })).status).toBe('serving');
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { status: 'syncing' })).status).toBe('syncing');
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { status: 'failed' })).status).toBe('failed');
  });

  it('reports an unrecognized or absent status as unknown rather than serving', () => {
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { status: 'somethingNew' })).status).toBe('unknown');
    expect(mapCaptionItem(makeCaption('standard')).status).toBe('unknown');
  });

  it('surfaces failureReason only when the API supplies one', () => {
    const failed = mapCaptionItem(makeCaption('standard', 'unknown', {
      status: 'failed',
      failureReason: 'processingFailed',
    }));
    expect(failed.failureReason).toBe('processingFailed');
    expect(mapCaptionItem(makeCaption('standard')).failureReason).toBeNull();
  });

  it('narrows the documented audio track types and defaults the rest to unknown', () => {
    expect(mapCaptionItem(makeCaption('standard', 'primary')).audioTrackType).toBe('primary');
    expect(mapCaptionItem(makeCaption('standard', 'commentary')).audioTrackType).toBe('commentary');
    expect(mapCaptionItem(makeCaption('standard', 'descriptive')).audioTrackType).toBe('descriptive');
    expect(mapCaptionItem(makeCaption('standard', 'unexpected')).audioTrackType).toBe('unknown');
    expect(mapCaptionItem(makeCaption('standard', undefined)).audioTrackType).toBe('unknown');
  });

  it('exposes the uploader track label, empty for auto-generated tracks', () => {
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { name: 'English' })).name).toBe('English');
    expect(mapCaptionItem(makeCaption('asr', 'unknown', { name: '' })).name).toBe('');
  });

  it('resolves languageName to a human-readable name, falling back to the code', () => {
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { language: 'ja' })).languageName).toBe('Japanese');
    // getLanguageName only maps the localization languages (issue #105).
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { language: 'ko' })).languageName).toBe('ko');
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { language: undefined })).languageName).toBe('unknown');
  });

  it('passes lastUpdated through and nulls it when absent', () => {
    expect(mapCaptionItem(makeCaption('standard', 'unknown', { lastUpdated: '2026-07-12T09:27:27.554754Z' })).lastUpdated)
      .toBe('2026-07-12T09:27:27.554754Z');
    expect(mapCaptionItem(makeCaption('standard')).lastUpdated).toBeNull();
  });
});
