import { describe, expect, it } from 'bun:test';
import { youtube_v3 } from 'googleapis';
import { mapCaptionItem } from '../lib/youtube';

function makeCaption(
  trackKind: string | undefined = 'standard',
  audioTrackType: string | undefined = 'unknown',
): youtube_v3.Schema$Caption {
  return {
    id: 'caption-id',
    snippet: {
      videoId: 'video-id',
      language: 'en',
      trackKind,
      audioTrackType,
    },
  };
}

describe('mapCaptionItem', () => {
  it('classifies a standard caption as manual even when audioTrackType is unknown', () => {
    const caption = mapCaptionItem(makeCaption('standard', 'unknown'));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });

  it('classifies ASR captions as automatic', () => {
    const caption = mapCaptionItem(makeCaption('ASR', 'unknown'));

    expect(caption.trackKind).toBe('automatic');
    expect(caption.isAutoGenerated).toBe(true);
  });

  it('normalizes lowercase ASR values returned by the API', () => {
    const caption = mapCaptionItem(makeCaption('asr', 'unknown'));

    expect(caption.trackKind).toBe('automatic');
    expect(caption.isAutoGenerated).toBe(true);
  });

  it('classifies forced captions as automatic', () => {
    const caption = mapCaptionItem(makeCaption('forced', 'unknown'));

    expect(caption.trackKind).toBe('automatic');
    expect(caption.isAutoGenerated).toBe(true);
  });

  it('ignores audioTrackType when identifying automatic captions', () => {
    const caption = mapCaptionItem(makeCaption('standard', 'commentary'));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });

  it('falls back to manual for an unknown track kind', () => {
    const caption = mapCaptionItem(makeCaption('unexpected'));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });

  it('falls back to manual when track kind is absent', () => {
    const caption = mapCaptionItem(makeCaption(undefined));

    expect(caption.trackKind).toBe('manual');
    expect(caption.isAutoGenerated).toBe(false);
  });
});
