import chalk from 'chalk';
import { listCaptions } from '../lib/youtube';
import { debug, initCommand, withSpinner, writeStdout } from '../lib/utils';
import { getOutputFormat } from '../lib/config';
import { formatJson, formatTable, formatCsv } from '../lib/formatters';
import { ListCaptionsOptions } from '../types';

async function listCaptionsCommand(options: ListCaptionsOptions): Promise<void> {
  initCommand(options);

  // Extract video ID from options
  const videoId = options.videoId;
  if (!videoId) {
    throw new Error('Required: --video-id');
  }

  await withSpinner('Fetching captions...', 'Failed to fetch captions', async (spinner) => {
    debug(`Fetching captions for video: ${videoId}`);
    const captions = await listCaptions(videoId);

    spinner.succeed(`Found ${captions.length} caption track(s)`);
    console.log('');

    const outputFormat = await getOutputFormat(options.output);

    switch (outputFormat) {
      case 'json':
        await writeStdout(formatJson(captions) + '\n');
        break;

      case 'table':
        const tableData = captions.map(cap => ({
          id: cap.id,
          videoId: cap.videoId,
          language: cap.languageName,
          code: cap.language,
          kind: cap.trackKind,
          auto: cap.isAutoGenerated ? 'Yes' : 'No',
          // Whether the track is actually visible on the video, which is not
          // implied by either the language or the track kind.
          status: cap.status,
          draft: cap.isDraft ? 'Yes' : 'No',
        }));
        await writeStdout(formatTable(tableData) + '\n');
        break;

      case 'text':
        // Header and rows in one write so the whole payload is flushed together.
        await writeStdout(
          [
            ['id', 'videoId', 'language', 'code', 'name', 'kind', 'autoGenerated', 'status', 'isDraft'].join('\t'),
            ...captions.map(cap => [
              cap.id,
              cap.videoId,
              cap.languageName,
              cap.language,
              cap.name,
              cap.trackKind,
              cap.isAutoGenerated ? 'true' : 'false',
              cap.status,
              cap.isDraft ? 'true' : 'false',
            ].join('\t')),
          ].join('\n') + '\n'
        );
        break;

      case 'csv':
        const csvData = captions.map(cap => ({
          id: cap.id,
          videoId: cap.videoId,
          language: cap.languageName,
          languageCode: cap.language,
          name: cap.name,
          trackKind: cap.trackKind,
          isAutoGenerated: cap.isAutoGenerated,
          isAutoSynced: cap.isAutoSynced,
          isClosedCaptions: cap.isClosedCaptions,
          isLarge: cap.isLarge,
          isEasyReader: cap.isEasyReader,
          isDraft: cap.isDraft,
          status: cap.status,
          audioTrackType: cap.audioTrackType,
          failureReason: cap.failureReason ?? '',
          lastUpdated: cap.lastUpdated ?? '',
        }));
        await writeStdout(formatCsv(csvData) + '\n');
        break;

      case 'pretty':
      default:
        if (captions.length === 0) {
          console.log(chalk.yellow('No captions found for this video.'));
          console.log('');
          break;
        }

        captions.forEach((cap, index) => {
          const kindLabel = cap.trackKind === 'automatic' ? chalk.yellow('automatic (YouTube-generated)') : chalk.green('manual (user-uploaded)');
          // A track that is a draft, still syncing, or failed shows nothing to
          // viewers. Only `serving` and published means the captions are live.
          //
          // isDraft is checked FIRST and independently of status: a draft track
          // is reported by the API as `status: serving` (live-verified by
          // uploading one with --draft), so keying visibility off status alone
          // would announce an invisible track as visible.
          const isLive = cap.status === 'serving' && !cap.isDraft;
          const visibility = cap.isDraft
            ? chalk.yellow('draft (not visible to viewers)')
            : cap.status === 'serving'
              ? chalk.green('serving (visible to viewers)')
              : cap.status === 'syncing'
                ? chalk.yellow('syncing (not visible yet)')
                : cap.status === 'failed'
                  ? chalk.red(`failed${cap.failureReason ? ` (${cap.failureReason})` : ''}`)
                  : chalk.gray('unknown');

          // Attributes worth a line only when they are set. Every one of these
          // is false/default on the overwhelming majority of real tracks, so
          // printing them unconditionally would bury the fields that decide
          // whether the captions work. Use --output csv for the full record.
          const attributes = [
            cap.isClosedCaptions ? 'closed captions' : null,
            cap.isLarge ? 'large text' : null,
            cap.isEasyReader ? 'easy reader' : null,
            cap.isAutoSynced ? 'auto-synced timing' : null,
            cap.audioTrackType !== 'unknown' ? `${cap.audioTrackType} audio` : null,
          ].filter((a): a is string => a !== null);

          const title = cap.name ? `${cap.languageName} (${cap.language}) - ${cap.name}` : `${cap.languageName} (${cap.language})`;
          console.log(chalk.bold(`${index + 1}. ${title}`));
          console.log(chalk.gray('   Caption ID: ') + chalk.yellow(cap.id));
          console.log(chalk.gray('   Source:     ') + kindLabel);
          console.log(chalk.gray('   Visibility: ') + visibility);
          if (attributes.length > 0) {
            console.log(chalk.gray('   Attributes: ') + attributes.join(', '));
          }
          if (cap.lastUpdated) {
            console.log(chalk.gray('   Updated:    ') + cap.lastUpdated);
          }
          if (!isLive) {
            console.log(chalk.gray('   Note:       ') + chalk.yellow('this track is not currently shown on the video'));
          }
          console.log('');
        });
        break;
    }
  });
}

export = listCaptionsCommand;
