import ora from 'ora';
import chalk from 'chalk';
import { listCaptions } from '../lib/youtube';
import { error, setVerbose, debug } from '../lib/utils';
import { getOutputFormat } from '../lib/config';
import { formatJson, formatTable, formatCsv } from '../lib/formatters';
import { OutputOption, VerboseOption } from '../types';

async function listCaptionsCommand(videoId: string, options: OutputOption & VerboseOption): Promise<void> {
  // Enable verbose mode if requested
  if (options.verbose) {
    setVerbose(true);
    debug('Verbose mode enabled');
  }

  const spinner = ora('Fetching captions...').start();

  try {
    debug(`Fetching captions for video: ${videoId}`);
    const captions = await listCaptions(videoId);

    spinner.succeed(`Found ${captions.length} caption track(s)`);
    console.log('');

    const outputFormat = await getOutputFormat(options.output);

    switch (outputFormat) {
      case 'json':
        console.log(formatJson(captions));
        break;

      case 'table':
        const tableData = captions.map(cap => ({
          id: cap.id,
          videoId: cap.videoId,
          language: cap.languageName,
          code: cap.language,
          kind: cap.trackKind,
          auto: cap.isAutoGenerated ? 'Yes' : 'No',
        }));
        console.log(formatTable(tableData));
        break;

      case 'text':
        console.log(['id', 'videoId', 'language', 'code', 'kind', 'autoGenerated'].join('\t'));
        captions.forEach(cap => {
          console.log([
            cap.id,
            cap.videoId,
            cap.languageName,
            cap.language,
            cap.trackKind,
            cap.isAutoGenerated ? 'true' : 'false',
          ].join('\t'));
        });
        break;

      case 'csv':
        const csvData = captions.map(cap => ({
          id: cap.id,
          videoId: cap.videoId,
          language: cap.languageName,
          languageCode: cap.language,
          trackKind: cap.trackKind,
          isAutoGenerated: cap.isAutoGenerated,
          isClosedCaptions: cap.isClosedCaptions,
          isLarge: cap.isLarge,
          isEasyReader: cap.isEasyReader,
          isDraft: cap.isDraft,
        }));
        console.log(formatCsv(csvData));
        break;

      case 'pretty':
      default:
        if (captions.length === 0) {
          console.log(chalk.yellow('No captions found for this video.'));
          console.log('');
          break;
        }

        captions.forEach((cap, index) => {
          console.log(chalk.bold(`${index + 1}. ${cap.languageName} (${cap.language})`));
          console.log(chalk.gray('   Caption ID: ') + chalk.yellow(cap.id));
          console.log(chalk.gray('   Track Kind: ') + (cap.trackKind === 'ASR' ? chalk.yellow('Auto-generated') : chalk.green(cap.trackKind)));
          console.log(chalk.gray('   Auto:       ') + (cap.isAutoGenerated ? chalk.green('Yes') : chalk.yellow('No')));
          console.log('');
        });
        break;
    }
  } catch (err) {
    spinner.fail('Failed to fetch captions');
    console.log('');
    error((err as Error).message);
    process.exit(1);
  }
}

export = listCaptionsCommand;
